### ISSUE TITLE
Set up Travis-CI integration for flake8 checking

### ISSUE THREAD

**Issue by davehunt** [mozilla/marketplace-tests-gaia#105]
We should use Travis-CI for basic code checking. In order to do this, we need to set up `.travis.yml` as follows:
```yml
language: python
python: 2.7
install: "pip install flake8"
script: "flake8 ."
```

In order to ignore line lengths, also include a `setup.cfg` file:
```ini
[flake8]
ignore=E501
```
